---
- name: Attempting to overlay public ssh configurations, if applicable
  tags: auth
  become: true
  no_log: true
  authorized_key:
    comment: "{{ item.value.comment|default(item.key) }}"
    exclusive: "{{ item.value.exclusive|default(omit) }}"
    key: "{{ item.value.key }}"
    key_options: "{{ item.value.key_options|default([])|join(',') }}"
    manage_dir: "{{ item.value.manage_dir|default(omit) }}"
    path: "{{ item.value.path|default(omit) }}"
    state: "{{ item.value.state|default(omit) }}"
    user: "{{ item.key }}"
    validate_certs: "{{ item.value.validate_certs|default(omit) }}"
  with_dict: "{{ auth_users }}"
  when:
    - auth_users|length > 0
    - item.key is defined
    - item.value.key is defined
...
